### ISSUE TITLE
In page builder: Persistant cursor position and filter across components. (recommended by Trent)

### ISSUE THREAD

**Issue by Code-Ergo-Sum** [insum-labs/insum-apex-pro#6]
Suppose you've clicked on the property "Static ID" for a given component, and you click on another component in TreeView. The current behavior is that the property editor will show the properties from top-to-bottom, so if you want to edit that component's Static ID you'd have to scroll down.
A feature (which could be turned on/off) would be to have the new component also have it's cursor on Static ID, and to have this property scrolled into view.

Another similar feature is to have the "Filter Properties" bar persist as you move from component to component. So if you want to filter for, say, the word "column", as you click from component to component that filter will be applied each time (the current behavior is that the filter is reset).

**Comment by jaistudy1996** [comment]
These features were added.
